
services:
  php:
    build:
      context: ./php
    container_name: taskmanager_php
    volumes:
      - ../:/var/www/TaskManager:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    depends_on:
      - db
    networks:
      - taskmanager_network

  nginx:
    image: nginx:latest
    container_name: taskmanager_nginx
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/TaskManager
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - taskmanager_network

  db:
    image: mysql:8.4
    container_name: taskmanager_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "3307:3306"
    volumes:
    - taskmanager_db_data:/var/lib/mysql
    networks:
      - taskmanager_network

networks:
  taskmanager_network:
    driver: bridge

volumes:
  taskmanager_db_data:
    driver: local